version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - ${DB_NAME}:80
    privileged: true
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/apache/*.conf /etc/apache2/sites-enabled/
      - ${PROJECT_PATH}:/var/www/html
      - node_modules:/var/www/html/node_modules
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    volumes:
      - ./logs:/var/log/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - ${PMA_PORT}:80

volumes:
  mysql:
  node_modules: